spring:
  application:
    name: sp_parking_api
  datasource:
    url: jdbc:mysql://localhost:3306/parking
    username: ENC(UZKxgIDuA26/DA2/J6Btf2eEa8RuaOaS)
    password: ENC(G3qSSN0DpypzQtFhfSiuUWv4c/4C01rT)
    #    url: jdbc:mysql://localhost:3306/parking
    #    username: parking_api
    #    password: parking_api!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  ## Hibernate
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: false
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

## Tomcat
server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    connection-timeout: 20000
    accept-count: 100
    keep-alive-timeout: 100

parking:
  openapi:
    url: http://openapi.seoul.go.kr:8088
    key: ENC(9nnh9Hl/CDacvhOcndqPMYgRXVoJ73zsGWdwEP89BWkBGw32L052NQ==)
    type: json
    service: GetParkInfo
  insert:
    batch:
      flag: 100

holiday:
  openapi:
    url: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?
    key: ENC(q6Fv+K0h/DzsZ2hXuWSr1F+ymI0kIekJ7OZj333cCZOoIgUDVP2FE4MDE/mqUYAkHMlemC3CFaw5L5jfCm36+xbmDtjJGsFmAWpfP1KrPvaJhQ8gIP0ekCVCpd1rlrfGiDT5P/3S9lE2T8yrU3ageA==)





## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

## Logging
logging:
  level:
    root: info
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

## actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"